version: '3.8'

services:
  db:
    image: mysql:8
    container_name: mysql_db
    environment:
      MYSQL_DATABASE: franquicia_db
      MYSQL_ROOT_PASSWORD: admin
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5


  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: franquicia_app
    ports:
      - "8080:8080"
    environment:
      SPRING_R2DBC_URL: r2dbc:mysql://db:3306/franquicia_db
      SPRING_R2DBC_USERNAME: root
      SPRING_R2DBC_PASSWORD: admin
      SCHEMA_VALIDATION_JDBC_URL: jdbc:mysql://db:3306/franquicia_db
      SCHEMA_VALIDATION_USERNAME: root
      SCHEMA_VALIDATION_PASSWORD: admin
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/franquicia_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: admin
    depends_on:
      db:
        condition: service_healthy
    restart: always

volumes:
  db_data: