spring:
  r2dbc:
    url: ${SPRING_R2DBC_URL:r2dbc:mysql://localhost:3306/franquicia_db}
    username: ${SPRING_R2DBC_USERNAME:root}
    password: ${SPRING_R2DBC_PASSWORD:admin}
    initialization-mode: never
  main:
    web-application-type: reactive
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/franquicia_db}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:admin}
    driver-class-name: com.mysql.cj.jdbc.Driver

  sql:
    init:
      mode: never
  flyway:
    enabled: true
    locations: classpath:db/migration
    connectRetries: 10
    connectRetriesInterval: 5s


management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
logging:
  level:
    org.flywaydb: DEBUG
